### ISSUE TITLE
OSX10.11 sublime-text3 install failed, can not find Cscope.sublime-settings

### ISSUE THREAD

**Issue by chenji-kael** [ameyp/CscopeSublime#46] opened 2016-04-04 10:07 UTC
I installed this plugin through Packet Control, after install finished,I find that nothing exited in the packet dir ,but I can find Cscope.sublime-package in /Users/chenji/Library/Application Support/Sublime Text 3/Installed Packages/Cscope.sublime-package,
It guess something wrong happens but no hit pop out.

**Comment by Morphin3** [comment] 2016-04-28 11:40
+1.

**Comment by vanrijn** [comment] 2016-05-15 23:38
Hm, thanks for the bug report. Can you guys help me understand what you're doing? If you can give me some reproduction steps that I can try here, that would be helpful. Thanks!

**Comment by guduo** [comment] 2016-05-23 16:09
same error. After install through Packet Contro, can't find the CscopeSublime.sublime-settings in /Users/xxx/Library/Application Support/Sublime Text 3/Packages/User

**Comment by guduo** [comment] 2016-05-23 16:11
same error. After install through Packet Contro, can't find the CscopeSublime.sublime-settings in /Users/xxx/Library/Application Support/Sublime Text 3/Packages/User

**Comment by guduo** [comment] 2016-05-23 16:12
same error. After install through Packet Contro, can't find the CscopeSublime.sublime-settings in /Users/xxx/Library/Application Support/Sublime Text 3/Packages/User

**Comment by guduo** [comment] 2016-05-23 16:13
same error. After install through Packet Contro, can't find the CscopeSublime.sublime-settings in /Users/xxx/Library/Application Support/Sublime Text 3/Packages/User

**Comment by vanrijn** [comment] 2016-05-25 03:17
Okay, you're not giving me much to go on here. Please tell me exactly what you're doing (reproduction steps), and exactly what you see (a screenshot would be great). Also, please open the console (Control+`) and copy/paste the error that you see there. Otherwise there's nothing for me to go on here and I'm going to have to close this comment since it's currently not actionable. Thanks.

**Comment by vanrijn** [comment] 2016-05-25 04:19
I think I understand. IIUC, we didn't have anything in the Preferences > Package Settings for CscopeSublime. My recent commit should fix this. Please reopen this if I'm misunderstanding or verify that I understood correctly. Thanks! =:)

**Closed by vanrijn** 2016-05-25 04:19 UTC
