### ISSUE TITLE
CscopeSublimeWorker error when looking up symbols in Sublime Text 2

### ISSUE THREAD

**Issue by Daedrus** [ameyp/CscopeSublime#26] opened 2013-06-19 15:00 UTC
I get this whenever I try to look something up:

Traceback (most recent call last):
  File ".\cscope.py", line 334, in <lambda>
  File ".\cscope.py", line 341, in update_status
AttributeError: 'CscopeSublimeWorker' object has no attribute 'output'

**Comment by vanrijn** [comment] 2016-05-16 00:39
Hey guys, sorry there hasn't been any activity on this. I don't have a Windows environment or anything older than OS X 10.11. It seems that there's 2 things here:

1) OS (Windows 7 and OS X 10.8.4)
2) Sublime Text 2

I don't have any of these things. I'm more than willing to look at patches to address this, but I don't have anything in place right now to try to help.

The effort and work it took to move from Sublime Text 2 to Sublime Text 3 was definitely non-trivial. Are you guys able to try CscopeSublime with Sublime Text 3 in your current OS'es and see if this problem still exists? I'm guessing the problem is ST2-related. 

If you could try ST3 and see if the problem is solved, maybe that's a good enough solution? I don't think we were planning on supporting ST2 anymore going forward, to be honest. Or at least I wasn't.

Please let me know what you think. Thanks!

**Comment by vanrijn** [comment] 2017-07-05 03:30
Ok, I'm going to close this. I haven't gotten any help on this in more than a year and I'd encourage people to use ST3 rather than ST2 anyway.

**Closed by vanrijn** 2017-07-05 03:30 UTC
